### PR TITLE
 Implement an io.Reader for embedding and attaching files.

### PR DESCRIPTION
**Pull request by jkak**
add below func() for attaching files from io.Reader for attachments: 
EmbedReader(), AttachReader(), fileFromFilename(), fileFromReader()
update  Embed(), Attach() and appendFile() for use above io.Reader.

The above code has been running steadily for more than a month on line.

### CODE REVIEW

**Comment by ivy** [comment]
It looks like @arbarlow's authorship credit was lost in your commit history. Thanks for testing out go-gomail#78 though. :+1:

I'll review and merge when I have some spare time this week.

**Comment by jkak** [comment]
commit history:

commit d8f857a4ac93457dac3abefa15ca4aa2f2a1cb68
Author: jungle85gopy <jungle85gopy@gmail.com>
Date:   Fri May 25 00:38:50 2018 +0800

    add go-gomail/gomail Pull request #78
    PR: Accept io.Reader for Attach and Embed #78
    thanks for arbarlow

but I'm sure I forgot to thanks arbarlow in my PR. sorry.

**Comment by arbarlow** [comment]
I have no issues with someone using my code like so, apologies I haven't had time to merge this stuff myself into go-mail, we are extensive users of `gomail` at my current company though, so happy to help with things

**Comment by ivy** [comment]
Sorry for the wait. I've merged this PR in 873972a5de9075558283b053e5ff6b0987bcdefd.

**Pull request closed without merging**
